---

- name: Download Chrome Stable
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: ~/google-chrome-stable_current_amd64.deb

- name: Install Chrome Stable
  apt:
    deb: ~/google-chrome-stable_current_amd64.deb

- name: Cleanup
  file:
    path: ~/google-chrome-stable_current_amd64.deb
    state: absent
