---

- name: Install PDF libs
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: False
  vars:
    packages:
      - xvfb
      - libfontconfig
      - libpoppler-glib-dev
      - libpoppler-glib8
      - libpoppler-dev

- name: Install PDF command line tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: False
  vars:
    packages:
      - wkhtmltopdf
      - poppler-utils
