---

- hosts: _railway_ec2_development_ami
  remote_user: ansible
  become: yes

  pre_tasks:
    - name: Set cflags and pkgconfig for all build scripts
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value}}"
      with_items:
        - key: CFLAGS
          value: -O3
        - key: CXXFLAGS
          value: -O3

  roles:
    - role: ami/purge_services
      tags: ami_purge_services

    - role: ami/time
      tags: ami_time

    - role: ami/cron
      tags: ami_cron

    - role: ami/ufw
      tags: ami_ufw

    - role: ami/ssh
      tags: ami_ssh

    - role: ami/buildtools
      tags: ami_buildtools

    - role: ami/python
      tags: ami_python

    - role: ami/rust
      tags: ami_rust

    - role: ami/node
      tags: ami_node

    - role: ami/redis
      tags: ami_redis

    - role: ami/postgres
      tags: ami_postgres

    - role: ami/sqlite
      tags: ami_sqlite

    - role: ami/ffmpeg
      tags: ami_ffmpeg

    - role: ami/pdf
      tags: ami_pdf

    - role: ami/libjxl
      tags: ami_libjxl

    - role: ami/libheif
      tags: ami_libheif

    - role: ami/libspng
      tags: ami_libspng

    - role: ami/mozjpeg
      tags: ami_mozjpeg

    - role: ami/openjpeg
      tags: ami_openjpeg

    - role: ami/imagemagick
      tags: ami_imagemagick

    - role: ami/libvips
      tags: ami_libvips

    - role: ami/chrome
      tags: ami_chrome

    - role: ami/ruby
      param_version: "{{ ruby_version }}"
      tags: ami_ruby

    - role: aws/cloudwatch
      param_nam/: "{{ ansible_environment }}"
      param_hostname: ami
      param_process_type: ami
      tags: aws_cloudwatch

    - role: ami/dist_upgrade
      tags: ami_dist_upgrade
