---

- hosts: localhost
  gather_facts: False
  pre_tasks:

    - community.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ app_name }}-ec2-{{ ansible_environment }}-ami"
          instance-state-name: ["running"]
      register: register_instance_info

  roles:
    - role: aws/ami_create
      param_name: ami
      param_instance_id: "{{ register_instance_info.instances[0].instance_id }}"
      tags: aws_ami_create

    - role: aws/ec2_destroy
      param_instance_id: "{{ register_instance_info.instances[0].instance_id }} "
      tags: aws_ec2_destroy
