---

- import_playbook: contribute_bootstrap.yml

- hosts: localhost
  gather_facts: False

  tasks:

    - name: Copy development vault to project
      copy:
        src: ../railway-credentials/development_vault
        dest: inventories/development/group_vars/all/vault
        mode: 0600

    - name: Copy production vault to project
      copy:
        src: ../railway-credentials/production_vault
        dest: inventories/production/group_vars/all/vault
        mode: 0600

    - name: Copy development EC2 key pair to project
      copy:
        src: ../railway-credentials/ansible-ec2-development.pem
        dest: roles/aws_ec2_create/files/ansible-ec2-development.pem

    - name: Copy production EC2 key pair to project
      copy:
        src: ../railway-credentials/ansible-ec2-production.pem
        dest: roles/aws_ec2_create/files/ansible-ec2-production.pem
