---

- hosts: _railway_ec2_production_*
  remote_user: ansible
  become: yes
  become_user: app
  gather_facts: false

  roles:
    - role: app_deploy
      param_name: production
      param_branch: "{{ version | default('main') }}"
      tags: app_deploy

- hosts: _railway_ec2_production_webserver
  remote_user: ansible
  become: yes
  gather_facts: false

  roles:
    - role: app_deploy_precompile
      param_name: production
      tags: app_deploy_precompile

- hosts: _railway_ec2_production_control
  remote_user: ansible
  become: yes
  gather_facts: false

  roles:
    - role: app_deploy_migrate
      param_name: production
      tags: app_deploy_migrate

- hosts: _railway_ec2_production_webserver
  serial: 1
  remote_user: ansible
  become: yes
  gather_facts: false

  roles:
    - role: app_deploy_application_server_restart
      param_name: production
      param_group: "{{ group_id|default(0) }}"
      tags: app_deploy_application_server_restart

- hosts: _railway_ec2_production_worker
  serial: 1
  remote_user: ansible
  become: yes
  gather_facts: false

  roles:
    - role: app_deploy_worker_server_restart
      param_name: production
      tags: app_deploy_worker_server_restart
