---

- name: Download libvips
  unarchive:
    src: https://github.com/libvips/libvips/releases/download/v{{ config_vips_version }}/vips-{{ config_vips_version }}.tar.gz
    dest: ~/
    remote_src: True

- name: Compile vips
  command: "{{ item }}"
  args:
    chdir: ~/vips-{{ config_vips_version }}
  with_items:
    - ./configure
    - make
    - make install

- name: Cleanup
  file:
    path: ~/vips-{{ config_vips_version }}
    state: absent
