---

- name: Add user
  user:
    name: "{{ param_name }}"
    state: present

- name: Set comment
  user:
    name: "{{ param_name }}"
    comment: "{{ param_comment }}"
  when: param_comment != ""

- name: Set shell
  user:
    name: "{{ param_name }}"
    shell: "{{ param_shell }}"

- name: Create .ssh directory
  file:
    path: ~{{ param_name }}/.ssh
    state: directory
    owner: "{{ param_name }}"
    group: "{{ param_name }}"
    mode: 0700

- name: Copy authorized keys from ubuntu user
  copy:
    remote_src: yes
    src: ~ubuntu/.ssh/authorized_keys
    dest: ~{{ param_name }}/.ssh/authorized_keys
    owner: "{{ param_name }}"
    group: "{{ param_name }}"
    mode: 0600

- name: Add sudo rights
  copy:
    content: "{{ param_name }} ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/{{ param_name }}
    mode: 0600
  when: param_sudo
