---

- name: Destroying target group named {{ app_name }}-alb-tg-{{ ansible_environment }}-{{ param_name }}
  community.aws.elb_target_group:
    name: "{{ app_name }}-alb-tg-{{ ansible_environment }}-{{ item }}"
    state: absent
  loop:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9

- name: Destroying application load balancer named {{ app_name }}-alb-{{ ansible_environment }}-{{ param_name }}
  community.aws.elb_application_lb:
    name: "{{ app_name }}-alb-{{ ansible_environment }}-{{ item }}"
    state: absent
  loop:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
