---

- block:

    - name: Install libvips package if not building image libraries from source
      apt:
        name: libvips-tools
        state: present
        update_cache: False

  when: ansible_build_image_libs == false

- block:

    - name: Download libvips
      unarchive:
        src: https://github.com/libvips/libvips/releases/download/v{{ ansible_libvips_version }}/vips-{{ ansible_libvips_version }}.tar.gz
        dest: ~/
        remote_src: True

    - name: Compile vips
      command: "{{ item }}"
      args:
        chdir: ~/vips-{{ ansible_libvips_version }}
      with_items:
        - ./configure
        - make
        - make install

    - name: Cleanup
      file:
        path: ~/vips-{{ ansible_libvips_version }}
        state: absent

  when: ansible_build_image_libs == true
