---

- name: Remove postfix 
  apt:
    name: postfix
    state: absent

- name: Remove apport
  apt:
    name: apport
    state: absent

- name: Remove at
  apt:
    name: at
    state: absent

- name: Remove cups
  apt:
    name: cups
    state: absent

- name: Remove modemmanager
  apt:
    name: modemmanager
    state: absent
