---

- name: Install ufw
  apt:
    name: ufw
    state: present
    update_cache: False

- name: Copy ufw configuration 
  copy:
    src: "{{ item }}"
    dest: /etc/ufw/{{ item }} 
    force: yes
  with_items:
      - user.rules 
      - user6.rules
  notify: Reload ufw    

- name: Enable ufw
  service:
    name: ufw
    enabled: yes

- name: Start ufw
  service:
    name: ufw
    state: started  
