---

- block:

    - name: Download mozjpeg
      unarchive:
        src: https://github.com/mozilla/mozjpeg/archive/v{{ config_mozjpeg_version }}.tar.gz
        dest: ~/
        remote_src: True

    - name: Compile mozjpeg
      command: "{{ item }}"
      args:
        chdir: ~/mozjpeg-{{ config_mozjpeg_version }}
      with_items:
        - cmake -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib/x86_64-linux-gnu
        - make
        - make install

    - name: Cleanup
      file:
        path: ~/mozjpeg-{{ config_mozjpeg_version }}
        state: absent

  when: ansible_build_image_libs == true
