
---

- name: Install Ruby {{ param_version }} for app
  shell: $(which su) - app -c "RUBY_CONFIGURE_OPTS='--with-jemalloc' rbenv install {{ param_version }} --verbose >> ~/ruby_log.txt"
  args:
    creates: ~app/.rbenv/versions/{{ param_version }}

- name: Set global Ruby {{ param_version }}
  shell: $(which su) - app -c "rbenv global {{ param_version }}"
  args:
    creates: ~app/.rbenv/version

- name: Disable rdocs and ri
  copy:
    content: "gem: --no-document"
    dest: ~app/.gemrc
    owner: app
    group: app
    mode: 0600
