---

- name: Install cron daemon
  apt:
    name: cron
    state: present
    update_cache: False

- name: Enable cron daemon.
  service:
    name: cron
    enabled: yes

- name: Start cron daemon.
  service:
    name: cron
    state: started
