---

- name: Install basic build tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: False
  vars:
    packages:
      - apt-transport-https
      - autoconf
      - automake
      - bison
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - default-jre
      - gcc
      - gnupg2
      - libaom3
      - libde265-0
      - libsystemd-dev
      - libtool
      - lsb-release
      - make
      - nasm
      - pkg-config
      - shared-mime-info
      - software-properties-common
      - tcl
      - ubuntu-keyring
      - unzip
      - x265

- name: Install dev
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: False
  vars:
    packages:
      - libaom-dev
      - libbrotli-dev
      - libcairo2-dev
      - libcfitsio-dev
      - libcurl4-openssl-dev
      - libde265-dev
      - libexif-dev
      - libexpat1-dev
      - libffi-dev
      - libfftw3-dev
      - libgif-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgsf-1-dev
      - libgsf-1-dev
      - libheif-dev
      - libimagequant-dev
      - libjemalloc-dev
      - liblcms2-dev
      - libmatio-dev
      - libopenexr-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpng-dev
      - libpq-dev
      - libreadline-dev
      - librsvg2-dev
      - libssl-dev
      - libtiff5-dev
      - libwebp-dev
      - libx265-dev
      - libxml2-dev
      - libxslt1-dev
      - libyaml-dev
      - libzstd-dev
      - zlib1g-dev
